// Code generated by "stringer -type=Software"; DO NOT EDIT.

package metadata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fooocus-1]
	_ = x[FooocusPlus-2]
	_ = x[RuinedFooocus-4]
}

const (
	_Software_name_0 = "FooocusFooocusPlus"
	_Software_name_1 = "RuinedFooocus"
)

var (
	_Software_index_0 = [...]uint8{0, 7, 18}
)

func (i Software) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Software_name_0[_Software_index_0[i]:_Software_index_0[i+1]]
	case i == 4:
		return _Software_name_1
	default:
		return "Software(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
