// Code generated by "stringer -type=MetadataVersion"; DO NOT EDIT.

package fooocus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[v21-21]
	_ = x[v22-22]
	_ = x[v23-23]
}

const _MetadataVersion_name = "v21v22v23"

var _MetadataVersion_index = [...]uint8{0, 3, 6, 9}

func (i MetadataVersion) String() string {
	i -= 21
	if i >= MetadataVersion(len(_MetadataVersion_index)-1) {
		return "MetadataVersion(" + strconv.FormatInt(int64(i+21), 10) + ")"
	}
	return _MetadataVersion_name[_MetadataVersion_index[i]:_MetadataVersion_index[i+1]]
}
