// Code generated by "stringer -linecomment -type=MetadataScheme"; DO NOT EDIT.

package fooocus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fooocus-0]
	_ = x[A1111-1]
}

const _MetadataScheme_name = "fooocusa1111"

var _MetadataScheme_index = [...]uint8{0, 7, 12}

func (i MetadataScheme) String() string {
	if i >= MetadataScheme(len(_MetadataScheme_index)-1) {
		return "MetadataScheme(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MetadataScheme_name[_MetadataScheme_index[i]:_MetadataScheme_index[i+1]]
}
